spring:
    application:
        name: booking
        
    profiles:
        active: dev

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/Bookings
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /documentation/swagger-ui/index.html
    operationsSorter: method
    disable-swagger-default-url: true
  packagesToScan: com.booking.booking.controllers

server:
  servlet:
    context-path: /

